### ISSUE TITLE
New prop for toc nav overflow-y

### ISSUE THREAD

**Issue by roualdes** [janosh/svelte-toc#33]
First off, thanks for this great package.  

I'm interested, though still learning Svelte (and CSS), in adding a prop for the following style

https://github.com/janosh/svelte-toc/blob/06da85303dcbe6bed1e31057447f5348e4220c84/src/lib/Toc.svelte#L184-L189

From issue #32, you say you'll accept PRs adding such features.  And I'm happy submit a PR, but I need some guidance.

I assume something like

```
  :where(aside.toc > nav) {
    overflow-y: var(--toc-nav-overlfow); 
    ...
}
```
is close to what I'm after.  How does one set the default to `scroll;`? 

Thanks in advance for pointing me in the right direction.

**Comment by janosh** [comment]
@roualdes The 2nd (optional) argument specifies the default:

```css
:where(aside.toc > nav) {
  overflow-y: var(--toc-nav-overflow, scroll); 
}
```

No objections to this change though I think we can call it `--toc-overflow` instead of `--toc-nav-overflow` since no other elements have a CSS rule containing `overflow`. And let's change the property from `overflow-y` to `overflow` so you can control both x and y.

```css
  overflow: var(--toc-overflow, auto scroll); 
```


Remember to document the new variable in the [readme](https://github.com/janosh/svelte-toc#--styling).
